// Code generated by mockery v2.10.4. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// ModelInfoRepositoryConfig is an autogenerated mock type for the ModelInfoRepositoryConfig type
type ModelInfoRepositoryConfig struct {
	mock.Mock
}

// IsMocked provides a mock function with given fields:
func (_m *ModelInfoRepositoryConfig) IsMocked() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
