// Code generated by mockery v2.10.4. DO NOT EDIT.

package mock

import (
	database "neural_storage/database/core/services/interactor/database"

	mock "github.com/stretchr/testify/mock"
)

// ModelStructureWeightsInfoRepositoryConfig is an autogenerated mock type for the ModelStructureWeightsInfoRepositoryConfig type
type ModelStructureWeightsInfoRepositoryConfig struct {
	mock.Mock
}

// Adapter provides a mock function with given fields:
func (_m *ModelStructureWeightsInfoRepositoryConfig) Adapter() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ConnParams provides a mock function with given fields:
func (_m *ModelStructureWeightsInfoRepositoryConfig) ConnParams() database.Params {
	ret := _m.Called()

	var r0 database.Params
	if rf, ok := ret.Get(0).(func() database.Params); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(database.Params)
	}

	return r0
}

// IsMocked provides a mock function with given fields:
func (_m *ModelStructureWeightsInfoRepositoryConfig) IsMocked() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
