// Code generated by mockery v2.10.4. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// NormalizerConfig is an autogenerated mock type for the NormalizerConfig type
type NormalizerConfig struct {
	mock.Mock
}
