version: '3.9'

services:
  postgres_db:
    extends:
      file: common-services.yml
      service: postgres_db
    env_file: ./database/.dev.env
    volumes:
      - ../database/data:/data/dbcp/
    ports:
      - 5432:5432
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    extends:
      file: common-services.yml
      service: migration
    env_file: ./migration/.dev.env
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: on-failure:3

  tarantool-db:
    extends:
      file: common-services.yml
      service: tarantool-db
    ports:
      - 3301:3301
    env_file:
      - ./cache/.dev.env

  cube-dev:
    extends:
      file: common-services.yml
      service: cube
    image: cosmtrek/air
    working_dir: /tmp/project
    entrypoint: ["/go/bin/air", "-c", "cube/.air.toml"]
    env_file:
      - ./cube/.dev.env
    ports:
      - 8080:8080
    volumes:
      - ../go.sum:/tmp/project/go.sum
      - ../go.mod:/tmp/project/go.mod
      - ../vendor/:/tmp/project/vendor
      - ../pkg:/tmp/project/pkg
      - ../cache:/tmp/project/cache
      - ../config:/tmp/project/config
      - ../database:/tmp/project/database
      - ../cmd/cube:/tmp/project/cmd/cube
      - ../cube:/tmp/project/cube
      - ../cube/.air.toml:/tmp/project/cube/.air.toml
      - ../cube/dev.yml:/tmp/config.yml
      - ../out/crypto:/tmp/crypto/
    depends_on:
      migration:
        condition: service_completed_successfully
    restart: always
