version: "3"
# https://taskfile.dev/#/installation

tasks:
  default:
    desc: Start dev environment
    cmds:
      - task: bootstrap-crypto
      - task: generate
      - task: dev:start

  lint:
    desc: Generates mocks for ports interfaces
    cmds:
      - golangci-lint run ./...

  generate:
    desc: Generates mocks for ports interfaces
    cmds:
      - go generate ./...
      - cd cube && swag init -d ../cmd/cube/,./  -g ../../cube/handlers/fabric.go --parseDependency

  dev:start:
    desc: Starts development backend
    vars:
      DOCKERCOMPOSE: ./docker/docker-compose.dev.yml
    cmds:
      - docker-compose -f {{.DOCKERCOMPOSE}} up --build

  dev:stop:
    desc: Stops development backend
    vars:
      DOCKERCOMPOSE: ./docker/docker-compose.dev.yml
    cmds:
      - docker-compose -f {{.DOCKERCOMPOSE}} down

  prod:start:
    desc: Starts development backend
    vars:
      DOCKERCOMPOSE: ./docker/docker-compose.prod.yml
    cmds:
      - docker-compose -f {{.DOCKERCOMPOSE}} up -d

  prod:stop:
    desc: Stops development backend
    vars:
      DOCKERCOMPOSE: ./docker/docker-compose.prod.yml
    cmds:
      - docker-compose -f {{.DOCKERCOMPOSE}} down

  bootstrap-crypto:
    desc: Creates all crypto for authorization
    vars:
      OUT: ./out/crypto
    cmds:
      - mkdir -p {{.OUT}} | true
      - openssl genrsa -out {{.OUT}}/keypair.pem 2048
      - openssl rsa -in {{.OUT}}/keypair.pem -pubout -out {{.OUT}}/publickey.crt
      - openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in {{.OUT}}/keypair.pem -out {{.OUT}}/pkcs8.key
    status:
      - test -d {{.OUT}}

  test:lint:
    desc: Runs linters for golang code
    cmds:
      - golangci-lint run

  test:unit:
    desc: Runs unit test with coverage output
    deps:
      - dir:out
    vars:
      OUT: ./out/unit-coverage.out
      HTML: ./out/unit-coverage.html
    cmds:
      - go test -tags=unit -coverprofile={{.OUT}} -coverpkg=./... ./...
      - task: test:coverage
        vars:
          OUT: "{{.OUT}}"
          HTML: "{{.HTML}}"

  test:smoke:
    desc: Run smoke tests for project
    deps:
      - dir:out
    vars:
      OUT: ./out/smoke-coverage.out
      HTML: ./out/smoke-coverage.html
      DOCKERCOMPOSE: ./docker/docker-compose.smoke.yml
    cmds:
      - docker-compose -f {{.DOCKERCOMPOSE}} up --force-recreate -d
      - defer: docker-compose -f {{.DOCKERCOMPOSE}} down
      - go test -tags=smoke -coverprofile={{.OUT}} -coverpkg=./... ./...
      - task: test:coverage
        vars:
          OUT: "{{.OUT}}"
          HTML: "{{.HTML}}"

  test:coverage:
    desc: Build coverage report from tests result
    cmds:
      - go tool cover -html={{.OUT}} -o {{.HTML}}
      - go tool cover -func={{.OUT}}

  dir:out:
    desc: Creates out directiory
    cmds:
      - mkdir -p out
    status:
      - test -d out
