{
 "title": "Cube",
 "description": "Cube Application Metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(go_goroutines{job=\"$service\"}, instance)"
    }
   },
   {
    "name": "p",
    "label": "p",
    "query": {
     "query": "label_values(go_gc_duration_seconds{job=\"$service\"}, quantile)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(go_gc_duration_seconds{job=\"$service\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "req timings [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(v1_http_server_request_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{route}} {{instance}}"
    }
   ]
  },
  {
   "title": "ap1/v1/models",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "api/v1/models POST rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_models_call_add{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_models_ok_add{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_models_fail_add{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    },
    {
     "title": "api/v1/models GET rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_models_call_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_models_ok_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_models_fail_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    },
    {
     "title": "api/v1/models PATCH rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_models_call_update{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_models_ok_update{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_models_fail_update{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    },
    {
     "title": "api/v1/models DELETE rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_models_call_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_models_ok_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_models_fail_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "api/v1/models/weights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "api/v1/models/weights POST rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_weights_call_add{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_weights_ok_add{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_weights_fail_add{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    },
    {
     "title": "api/v1/models/weights GET rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_weights_call_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_weights_ok_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_weights_fail_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    },
    {
     "title": "api/v1/models/weights PATCH rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_weights_call_update{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_weights_ok_update{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_weights_fail_update{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    },
    {
     "title": "api/v1/models/weights DELETE rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_weights_call_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_weights_ok_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_weights_fail_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "api/v1/users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "api/v1/users GET rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_users_call{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_users_ok{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_users_fail{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "api/v1/login",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "api/v1/login POST rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_login_call{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "blocked [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_login_ok{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_login_fail{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    },
    {
     "title": "api/v1/login POST [blocked] rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_login_blocked{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "blocked [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_login_not_permitted{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "not permitted [{{instance}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "api/v1/registration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "api/v1/login POST rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_registration_call{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_registration_ok{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_registration_fail{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "api/v1/stat/models",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "api/v1/stat/models GET rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_models_stat_call_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_models_stat_ok_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_models_stat_fail_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "api/v1/stat/weights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "api/v1/stat/weights GET rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_weights_stat_call_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_weights_stat_ok_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_weights_stat_fail_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "api/v1/stat/users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "api/v1/stat/users GET rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_users_stat_call_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_users_stat_ok_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_users_stat_fail_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "api/v1/admin/users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "api/v1/admin/users GET rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_admin_users_call_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_admin_users_ok_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_admin_users_fail_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    },
    {
     "title": "api/v1/admin/users DELETE rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_admin_users_call_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_admin_users_ok_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_admin_users_fail_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "ap1/v1/admin/users/blocked",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "api/v1/admin/users/blocked GET rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_blocked_call_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_blocked_ok_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_blocked_fail_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    },
    {
     "title": "api/v1/admin/users DELETE rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_blocked_call_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_blocked_ok_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_blocked_fail_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    },
    {
     "title": "api/v1/admin/users PATCH rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_blocked_call_update{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_blocked_ok_update{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_blocked_fail_update{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "api/v1/admin/models",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "api/v1/admin/models GET rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_admin_models_call_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_admin_models_ok_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_admin_models_fail_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    },
    {
     "title": "api/v1/admin/models DELETE rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_admin_models_call_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_admin_models_ok_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_admin_models_fail_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "api/v1/admin/weights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "api/v1/admin/weighs GET rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_admin_weights_call_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_admin_weights_ok_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_admin_weights_fail_get{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    },
    {
     "title": "api/v1/admin/weights DELETE rps over $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(v1_cube_admin_weights_call_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "call [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_admin_weights_ok_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "ok [{{instance}}]"
      },
      {
       "expr": "rate(v1_cube_admin_weights_fail_delete{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "fail [{{instance}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "System Metircs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Off-Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=~\"$service\", instance=~\"$instance\"}",
       "legendFormat": "mspan inuse [{{instance}}]"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{job=~\"$service\", instance=~\"$instance\"}",
       "legendFormat": "mspan sys [{{instance}}]"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{job=~\"$service\", instance=~\"$instance\"}",
       "legendFormat": "mcache inuse [{{instance}}]"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{job=~\"$service\", instance=~\"$instance\"}",
       "legendFormat": "mcache sys [{{instance}}]"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{job=~\"$service\", instance=~\"$instance\"}",
       "legendFormat": "buck hash sys [{{instance}}]"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{job=~\"$service\", instance=~\"$instance\"}",
       "legendFormat": "gc sys [{{instance}}]"
      },
      {
       "expr": "go_memstats_other_sys_bytes{job=~\"$service\", instance=~\"$instance\"} - go_memstats_other_sys_bytes{job=\"$service\", instance=~\"$instance\"}",
       "legendFormat": "bytes of memory are used for other runtime allocations [{{instance}}]"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=~\"$service\", instance=~\"$instance\"}",
       "legendFormat": "next gc [{{instance}}]"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"$service\", instance=~\"$instance\"}",
       "legendFormat": "heap alloc [{{instance}}]"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{job=\"$service\", instance=~\"$instance\"}",
       "legendFormat": "heap sys [{{instance}}]"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$service\", instance=~\"$instance\"}",
       "legendFormat": "heap idle [{{instance}}]"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$service\", instance=~\"$instance\"}",
       "legendFormat": "heap inuse [{{instance}}]"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=\"$service\", instance=~\"$instance\"}",
       "legendFormat": "heap released [{{instance}}]"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
       "legendFormat": "stack inuse [{{instance}}]"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{instance=~\"$instance\"}",
       "legendFormat": "stack sys [{{instance}}]"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=\"$service\", instance=~\"$instance\"}",
       "legendFormat": "sys [{{instance}}]"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=\"$service\", instance=~\"$instance\"} - go_memstats_frees_total{job=\"$service\", instance=~\"$instance\"}",
       "legendFormat": "count [{{instance}}]"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "timeseries",
     "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=\"$service\", instance=~\"$instance\"}[1m])",
       "legendFormat": "mallocs rate [{{instance}}]"
      }
     ]
    },
    {
     "title": "Rate of a Pointer Dereferences",
     "type": "timeseries",
     "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{job=\"$service\", instance=~\"$instance\"}[1m])",
       "legendFormat": "lookup rate [{{instance}}]"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"$service\", instance=~\"$instance\"}",
       "legendFormat": "count [{{instance}}]"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$service\", instance=~\"$instance\"}[1m])",
       "legendFormat": "alloc byte rate [{{instance}}]"
      }
     ]
    },
    {
     "title": "GC duration (quantile=$p)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$service\", instance=~\"$instance\", quantile=~\"$p\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}